### PR TITLE
Add diagonal PT and PT presets

### PR DESCRIPTION
**Pull request by fbosman**
Added PT-commands for diagonal moves.
Added PT-presets, including icons

Added extra buttons according to the documentation of JVC. Only shift and tilt were implemented, this pull adds diagonal moves.
Added extra buttons to control streaming on/of of the camera, next to the control of recording.
Added feedback about streaming status

### CODE REVIEW

**Comment by josephdadams** [comment]
Great job, @fbosman! One thing - you changed the name of the action from `joyStickOperationPan` to `joyStickOperationPT`. However, changing this action name will break the functionality of existing users. There are two options to fix. The easiest is to just change it back to `joyStickOperationPan`. The other option is to write an Upgrade Script for the module to convert the existing actions of existing users over to the new format. Which would you prefer?

**Comment by josephdadams** [comment]
Also, `package.json` will need the `version` changed from `1.0.9` to `1.0.10` to show a change in the version. Thanks!

**Comment by fbosman** [comment]
Oeps,

I think it must be changed back, can you do this or should I change it.

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 18 jan. 2022 om 15:02 heeft Joseph Adams ***@***.***> het volgende geschreven:

﻿
Great job, @fbosman! One thing - you changed the name of the action from joyStickOperationPan to joyStickOperationPT. However, changing this action name will break the functionality of existing users. There are two options to fix. The easiest is to just change it back to joyStickOperationPan. The other option is to write an Upgrade Script for the module to convert the existing actions of existing users over to the new format. Which would you prefer?

**Comment by fbosman** [comment]
Thank you for your great work!

Met vriendelijke groet,

Frans Bosman


Verstuurd vanaf mijn iPhone

Op 18 jan. 2022 om 16:47 heeft Joseph Adams ***@***.***> het volgende geschreven:

﻿
Done, I will merge and get this into core for you now

**Pull request merged**
